### ISSUE TITLE
import directory instead of default.nix

### ISSUE THREAD

**Issue by Ben-PH** [Eveeifyeve/Dotfiles#3]
https://github.com/Eveeifyeve/Dotfiles/blob/a202e72e4b8ee1f307f1865e6f6e0853016e8d02/hosts/eveeifyeve-mac/home.nix#L11

this should be `../../modules/home-manager`. that just brings in `default.nix`

**Comment by Eveeifyeve** [comment]
Fixed in https://github.com/Eveeifyeve/Dotfiles/commit/0ee8654c1eada8059305bd946c8102bc73eb60fe if this is a issue still please make a comment with a reopen.
